default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  port: 5432
  username: liggar
  password: Prayoga1!
  database: invoiced

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
